App\Entity\WebApp\Contact:
  type: entity
  table: contact
  repositoryClass: App\Repository\Doctrine\ContactRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 50
      nullable: false
    email:
      type: string
      length: 32
      nullable: false
    subject:
      type: string
      length: 50
      nullable: false
    message:
      type: text
      nullable: false
    createdAt:
      type: datetime
      nullable: false
    updatedAt:
        type: datetime
        nullable: false