App\Entity\WebApp\Observation:
  type: entity
  table: observation
  repositoryClass: App\Repository\Doctrine\ObservationRepository
  indexes:
    message:
      columns: [ message ]
  id:
    id:
      type: integer
      generator:
      strategy: AUTO
  fields:
    message:
      type: string
      length: 255
      nullable: false
    createdAt:
      type: datetime
      nullable: false
    updatedAt:
      type: datetime
      nullable: false
  manyToOne:
    user:
      targetEntity: App\Entity\WebApp\User
      inversedBy: observations
      joinColumn:
        name: user_id
        referencedColumnName: id
        nullable: true
        onDelete: "SET NULL"
    weatherStation:
      targetEntity: App\Entity\WebApp\WeatherStation
      inversedBy: observations
      joinColumn:
        name: weather_station_id
        nullable: false
        referencedColumnName: id
        onDelete: "CASCADE"