App\Entity\WebApp\Post:
  type: entity
  table: post
  repositoryClass: App\Repository\Doctrine\PostRepository
  id:
    id:
      type: integer
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      length: 50
      nullable: false
    description:
      type: text
      nullable: false
    createdAt:
      type: datetime
      nullable: false
    updatedAt:
      type: datetime
      nullable: false
  manyToOne:
    user:
      targetEntity: App\Entity\WebApp\User
      inversedBy: posts
      joinColumn:
        name: user_id
        nullable: true
        referencedColumnName: id
        onDelete: "SET NULL"