App\Entity\WebApp\User:
  type: entity
  table: "`user`"
  repositoryClass: App\Repository\Doctrine\UserRepository
  indexes:
    user_email:
      columns: [ email ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    firstname:
      type: string
      length: 100
      nullable: false
    lastname:
      type: string
      length: 100
      nullable: false
    email:
      type: string
      length: 100
      nullable: false
    password:
      type: string
      length: 255
      nullable: false
    roles:
      type: json
      nullable: false
    createdAt:
      type: datetime
      nullable: false
    updatedAt:
      type: datetime
      nullable: false
  oneToMany:
    posts:
      targetEntity: App\Entity\WebApp\Post
      mappedBy: user
      cascade: [ "persist", "merge"]
    observations:
      targetEntity: App\Entity\WebApp\Observation
      mappedBy: user
      cascade: [ "persist", "merge"]