App\Entity\WebApp\WeatherData:
  type: entity
  table: weather_data
  repositoryClass: App\Repository\Doctrine\WeatherDataRepository
  indexes:
      weather_data_date:
          columns: [ date ]
  id:
    id:
      type: integer
      generator:
        strategy: IDENTITY
  fields:
    temperature:
      type: decimal
      precision: 3
      scale: 1
      nullable: false
    soilTemperature:
      type: decimal
      precision: 3
      scale: 1
      nullable: true
    heatIndex:
      type: decimal
      precision: 3
      scale: 1
      nullable: false
    humidity:
      type: integer
      nullable: false
    leafWetness:
      type: integer
      nullable: true
    relativePressure:
      type: decimal
      precision: 5
      scale: 1
      nullable: false
    absolutePressure:
      type: decimal
      precision: 5
      scale: 1
      nullable: false
    windDirection:
      type: integer
      nullable: false
    windDirectionAvg:
      type: integer
      nullable: false
    windSpeed:
      type: decimal
      precision: 4
      scale: 1
      nullable: false
    windSpeedAvg:
      type: decimal
      precision: 4
      scale: 1
      nullable: false
    windGust:
      type: decimal
      precision: 4
      scale: 1
      nullable: false
    windMaxDailyGust:
      type: decimal
      precision: 4
      scale: 1
      nullable: false
    rainRate:
      type: decimal
      precision: 4
      scale: 1
      nullable: false
    rainEvent:
      type: decimal
      precision: 4
      scale: 1
      nullable: false
    rainHourly:
      type: decimal
      precision: 4
      scale: 1
      nullable: false
    rainDaily:
      type: decimal
      precision: 4
      scale: 1
      nullable: false
    rainWeekly:
      type: decimal
      precision: 4
      scale: 1
      nullable: false
    rainMonthly:
      type: decimal
      precision: 4
      scale: 1
      nullable: false
    rainYearly:
      type: decimal
      precision: 5
      scale: 1
      nullable: false
    solarRadiation:
      type: decimal
      precision: 5
      scale: 1
      nullable: false
    uv:
      type: integer
      nullable: false
    pm25:
      type: decimal
      precision: 4
      scale: 1
      nullable: true
    pm25Avg:
      type: decimal
      precision: 4
      scale: 1
      nullable: true
    humidex:
      type: decimal
      precision: 3
      scale: 1
      nullable: false
    dewPoint:
      type: decimal
      precision: 3
      scale: 1
      nullable: false
    windChill:
      type: decimal
      precision: 3
      scale: 1
      nullable: true
    cloudBase:
      type: integer
      nullable: false
    beaufortScale:
      type: integer
      nullable: false
    aqi:
      type: integer
      nullable: true
    aqiAvg:
      type: integer
      nullable: true
    lightningDate:
      type: datetime
      nullable: true
    lightningDistance:
      type: integer
      nullable: true
    lightningDaily:
      type: integer
      nullable: true
    createdAt:
      type: datetime
      nullable: false
    date:
        type: date
        nullable: true
  manyToOne:
    unit:
      targetEntity: App\Entity\WebApp\Unit
      joinColumn:
        name: unit_id
        referencedColumnName: id
        nullable: false
        onDelete: "CASCADE"
    weatherStation:
      targetEntity: App\Entity\WebApp\WeatherStation
      joinColumn:
        name: weather_station_id
        referencedColumnName: id
        nullable: false
        onDelete: "CASCADE"