doctrine:
    dbal:
      default_connection: default
      connections:
        default:
          driver: pdo_mysql
          host: '%env(BDD_DEFAULT_HOST)%'
          port: '%env(BDD_DEFAULT_PORT)%'
          dbname: '%env(BDD_DEFAULT_DBNAME)%'
          user: '%env(BDD_DEFAULT_USERNAME)%'
          password: '%env(BDD_DEFAULT_PASS)%'
          charset: UTF8
          server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/Resources/config/doctrine'
                prefix: 'App\Entity\WebApp'
                alias: App
