doctrine:
    dbal:
      default_connection: default
      url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/Resources/config/doctrine'
                prefix: 'App\Entity\WebApp'
                alias: App
