services:
    _defaults:
        autowire: true
        autoconfigure: true

    Behat\Context\:
        resource: '../features/Context/*'

    Behat\Context\UserContext:
        arguments:
            - '@App\Repository\UserRepository'
            - "@password_encoder"