Symfony\Component\Validator\ConstraintViolation:
    attributes:
        message:
            groups: ['constraint']
        propertyPath:
            groups: ['constraint']
        messageTemplate:
            groups: ['constraint']