App\Core\Tactician\Command\WeatherStation\RegisterWeatherStationCommand:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 5
                max: 50
        description:
            - NotBlank: ~
        shortDescription:
            - NotBlank: ~
            - Length:
                min: 10
                max: 255
        country:
            - NotBlank: ~
        address:
            - NotBlank: ~
        city:
            - NotBlank: ~
        postalCode:
            - NotBlank: ~
        lat:
            - NotBlank: ~
        lng:
            - NotBlank: ~
        model:
            - NotBlank: ~
        elevation:
            - NotBlank: ~
        reference:
            -   NotBlank: ~