App\Core\Tactician\Command\Unit\RegisterUnitCommand:
    properties:
        temperatureUnit:
            - NotBlank: ~
        speedUnit:
            - NotBlank: ~
        rainUnit:
            - NotBlank: ~
        solarRadiationUnit:
            - NotBlank: ~
        pmUnit:
            - NotBlank: ~
        humidityUnit:
            - NotBlank: ~
        cloudBaseUnit:
            - NotBlank: ~
        windDirUnit:
            - NotBlank: ~
        pressureUnit:
            - NotBlank: ~
        type:
            - NotBlank: ~