App\Core\Tactician\Command\Contact\RegisterContactCommand:
    properties:
        message:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~
        subject:
            - NotBlank: ~
        name:
            - NotBlank: ~