name: Full CI deploy process for Symfony
on:
    push:
        branches:
            - production
jobs:
    deploy:
        name: Meteo41 - Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install Open VPN
              run: |
                  sudo apt-get install openvpn
                  touch /tmp/config.ovpn && echo "${{ secrets.VPN_FILE }}" > /tmp/config.ovpn
                  touch /tmp/login && echo "${{ secrets.LOGIN_FILE }}" > /tmp/login

            - name: Connect VPN
              id: connect_vpn
              run: |
                  sudo openvpn --config /tmp/config.ovpn --auth-user-pass /tmp/login --daemon

            - name: Check Connect VPN
              run: echo ${{ steps.connect_vpn.outputs.STATUS }}

            - name: kill vpn
              if: always()
              run: sudo killall openvpn