name: Full CI deploy process for Symfony
on:
    push:
        branches:
            - production
jobs:
    deploy:
        name: Meteo41 - Deploy
        runs-on: ubuntu-latest
        steps:
            # —— Setup
            - name: Checkout
              uses: actions/checkout@v2

            # —— Install Open VPN
            - name: Install Open VPN
              run: |
                  sudo apt-get install openvpn

            # —— Connect to VPN
            - name: Connect VPN
              uses: golfzaptw/action-connect-ovpn@master
              id: connect_vpn
              with:
                  PING_URL: '192.168.9.32'
                  FILE_OVPN: '.github/vpn/config.ovpn'
                  SECRET: ${{ secrets.SECRET_USERNAME_PASSWORD }}
                  TLS_KEY: ${{ secrets.TLS_KEY }}
              env:
                  CA_CRT: ${{ secrets.CA_CRT }}
                  USER_CRT: ${{ secrets.USER_CRT }}
                  USER_KEY: ${{ secrets.USER_KEY }}

            # —— Verify web server ping
            - name: Check Connect VPN
              run: |
                  ping ${{ secrets.REMOTE_SSH_IP }} -c 10

            # —— Run SSH command for deploy
            - name: SSH to server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.REMOTE_SSH_IP }}
                  username: ${{ secrets.USER }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                      RELEASE=`date +%s`
                      mkdir ${{ secrets.TARGET_PATH }}/$RELEASE
                      cd ${{ secrets.TARGET_PATH }}/$RELEASE
                      git clone https://github.com/RusHiiii/meteo41.git .
                      cp ${{ secrets.TARGET_PATH }}/current/config/jwt/private.pem config/jwt/private.pem
                      cp ${{ secrets.TARGET_PATH }}/current/config/jwt/public.pem config/jwt/public.pem
                      cp ${{ secrets.TARGET_PATH }}/current/.env.local .env.local
                      composer install --no-dev --optimize-autoloader --quiet
                      npm install --quiet --loglevel=error
                      composer dump-env prod
                      bin/console cache:clear --env=prod --no-debug
                      yarn production
                      ln -sfn ${{ secrets.TARGET_PATH }}/$RELEASE ${{ secrets.TARGET_PATH }}/current

            # —— Kill VPN
            - name: Kill Open VPN
              if: always()
              run: sudo killall openvpn